"""
QuantEngine Pro - Strategy Base Class
======================================
Abstract base class for all trading strategies.

Every strategy must implement:
    - on_bar(bar, context) → Optional[Signal]
    - on_tick(tick, context) → Optional[Signal]  (optional for bar strategies)

The Signal dataclass carries all information needed by the execution layer
to place and manage orders.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

import pandas as pd


# =============================================================================
# Signal Types
# =============================================================================

class SignalType(str, Enum):
    """Order signal types."""
    BUY = "BUY"              # Open long position
    SELL = "SELL"            # Close long position
    SELL_SHORT = "SELL_SHORT"  # Open short position
    BUY_TO_COVER = "BUY_TO_COVER"  # Close short position
    CLOSE = "CLOSE"          # Close all positions for this symbol
    REBALANCE = "REBALANCE"  # Adjust position size (for multi-factor strategies)


@dataclass
class Signal:
    """
    Trading signal generated by a strategy.

    Attributes:
        timestamp: Signal generation time
        symbol: Trading symbol
        type: BUY/SELL/CLOSE/REBALANCE
        price: Target price (None = market price)
        quantity: Target quantity (None = use position sizing)
        stop_loss: Stop-loss price (optional)
        take_profit: Take-profit price (optional)
        confidence: Signal confidence 0.0-1.0
        metadata: Strategy-specific extra data
    """
    timestamp: datetime
    symbol: str
    type: SignalType
    price: Optional[float] = None
    quantity: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    confidence: float = 1.0
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        """Validate signal fields."""
        if self.confidence < 0 or self.confidence > 1:
            raise ValueError(f"Confidence must be 0-1, got {self.confidence}")


@dataclass
class StrategyContext:
    """
    Context passed to strategies on each bar/tick.

    Contains current state and historical data needed for decision making.

    Attributes:
        symbol: Current trading symbol
        timeframe: Bar frequency
        current_bar: Latest OHLCV bar (or tick)
        history: Historical bars DataFrame
        positions: Current positions for this strategy
        portfolio_value: Total portfolio value
        cash: Available cash
        metadata: Custom context data
    """
    symbol: str
    timeframe: str
    current_bar: pd.Series
    history: pd.DataFrame
    positions: Dict[str, Dict] = field(default_factory=dict)
    portfolio_value: float = 0.0
    cash: float = 0.0
    metadata: Dict[str, Any] = field(default_factory=dict)


# =============================================================================
# Base Strategy
# =============================================================================

class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.

    Subclasses must implement:
        - on_bar(bar, context) → Optional[Signal]
        - on_tick(tick, context) → Optional[Signal] (optional)

    Lifecycle:
        1. __init__()      - Set up strategy parameters
        2. on_start()      - Called when strategy is activated (optional)
        3. on_bar()/on_tick() - Called for each new data point
        4. on_stop()       - Called when strategy is deactivated (optional)

    Usage:
        class MyStrategy(BaseStrategy):
            def __init__(self, params):
                super().__init__(params)
                self.ma_period = params.get("ma_period", 20)

            def on_bar(self, bar, context):
                if bar.close > context.history['close'].rolling(20).mean().iloc[-1]:
                    return Signal(
                        timestamp=bar.timestamp,
                        symbol=context.symbol,
                        type=SignalType.BUY,
                        confidence=0.8,
                    )
                return None
    """

    def __init__(self, params: Optional[Dict] = None):
        """
        Initialize strategy with parameters.

        Args:
            params: Strategy-specific parameter dictionary
        """
        self.params = params or {}
        self.name = self.__class__.__name__
        self._is_running = False
        self._signal_count = 0

    def on_start(self) -> None:
        """
        Called when strategy is activated.

        Override to initialize state, load models, etc.
        Default implementation does nothing.
        """
        pass

    def on_stop(self) -> None:
        """
        Called when strategy is deactivated.

        Override to clean up resources, save state, etc.
        Default implementation does nothing.
        """
        pass

    @abstractmethod
    def on_bar(
        self,
        bar: pd.Series,
        context: StrategyContext,
    ) -> Optional[Signal]:
        """
        Process a new OHLCV bar and optionally generate a signal.

        This is the primary method for bar-based strategies (daily, hourly, etc.).
        Called once per bar per symbol.

        Args:
            bar: Latest OHLCV bar as a pandas Series with columns:
                 timestamp, open, high, low, close, volume
            context: StrategyContext with history, positions, portfolio info

        Returns:
            Signal to execute, or None for no action
        """
        ...

    def on_tick(
        self,
        tick: pd.Series,
        context: StrategyContext,
    ) -> Optional[Signal]:
        """
        Process a new tick and optionally generate a signal.

        Override for tick-based strategies. Default returns None.

        Args:
            tick: Latest tick data
            context: StrategyContext with current state

        Returns:
            Signal or None
        """
        return None

    def calculate_position_size(
        self,
        signal: Signal,
        context: StrategyContext,
        risk_per_trade: float = 0.02,
    ) -> float:
        """
        Calculate position size based on risk management rules.

        Default implementation uses fixed-fractional position sizing:
        position = (portfolio * risk_per_trade) / stop_distance

        Args:
            signal: The trading signal
            context: Current market context
            risk_per_trade: Fraction of portfolio to risk per trade (default 2%)

        Returns:
            Position size in units
        """
        if signal.type in (SignalType.CLOSE, SignalType.REBALANCE):
            return 0.0

        portfolio = context.portfolio_value or 1.0
        risk_amount = portfolio * risk_per_trade

        if signal.stop_loss and signal.price:
            stop_distance = abs(signal.price - signal.stop_loss) / signal.price
            if stop_distance > 0:
                return risk_amount / (stop_distance * signal.price)

        # Default: allocate 10% of portfolio
        return (portfolio * 0.1) / (signal.price or context.current_bar["close"])

    @property
    def signal_count(self) -> int:
        """Total number of signals generated by this strategy."""
        return self._signal_count

    def _record_signal(self, signal: Signal) -> Signal:
        """Increment signal counter and return the signal."""
        self._signal_count += 1
        return signal
